title: MUTH Boravy
logo: /assets/logo.jpg
description: Nuclear Engineering, PhD, Lecturer at ITC (Cambodia)
theme: jekyll-theme-minimal

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
